import type { ProfileFormValues } from '../utils/types';

export const FIELD_TO_SECTION: Record<string, string> = {
  firstName: 'basic-information',
  lastName: 'basic-information',
  aboutMe: 'basic-information',
  headshotUrl: 'basic-information',
  headshotFile: 'basic-information',
  major: 'education',
  graduationYear: 'education',
  graduationMonth: 'education',
  gpa: 'education',
  skills: 'skills',
  linkedinHandle: 'resume',
  githubHandle: 'resume',
  portfolioUrl: 'resume',
  resumeUrl: 'resume',
  resumeFile: 'resume',
  opportunities: 'work-preferences',
  openToRelocate: 'work-preferences',
  workEnvironments: 'work-preferences',
  city: 'location',
  state: 'location',
  zip: 'location',
  authorizedToWork: 'location',
  gender: 'personal-identities',
  ethnicities: 'personal-identities',
};

export const DEFAULT_VALUES: ProfileFormValues = {
  firstName: '',
  lastName: '',
  email: '',
  aboutMe: '',
  headshotUrl: '',
  headshotFile: null,
  major: '',
  graduationYear: '',
  graduationMonth: '',
  gpa: '',
  experiences: [],
  skills: [],
  linkedinHandle: '',
  githubHandle: '',
  portfolioUrl: '',
  resumeUrl: '',
  resumeFile: null,
  opportunities: [],
  openToRelocate: false,
  workEnvironments: [],
  city: '',
  state: '',
  zip: '',
  authorizedToWork: false,
  gender: '',
  ethnicities: [],
};
